# Data Analysis Intro

## Import Pandas

In [1]:
import pandas as pd

## Importing Data

In [2]:
names = ['id', 'title', 'year', 'rating', 'votes', 'length', 'genres']
data = pd.read_csv('ipynb-data-files/imdb_top_10000.txt', sep="\t", names=names, index_col=0)

## Advanced Data Selection

In [4]:
data[data['year'] > 1995]

,title,year,rating,votes,length,genres
id,,,,,,
tt0137523,Fight Club (1999),1999,8.8,458173,139 mins.,Drama|Mystery|Thriller
tt0133093,The Matrix (1999),1999,8.7,448114,136 mins.,Action|Adventure|Sci-Fi
tt1375666,Inception (2010),2010,8.9,385149,148 mins.,Action|Adventure|Sci-Fi|Thriller
tt0169547,American Beauty (1999),1999,8.6,338332,122 mins.,Drama
tt0499549,Avatar (2009),2009,8.1,336855,162 mins.,Action|Adventure|Fantasy|Sci-Fi
...,...,...,...,...,...,...
tt0118635,Aprile (1998),1998,6.7,1358,78 mins.,Comedy
tt0807721,Meduzot (2007),2007,7.0,1357,78 mins.,Drama
tt0339642,Daltry Calhoun (2005),2005,5.2,1357,100 mins.,Comedy|Drama|Music|Romance
tt0152836,Taal (1999),1999,6.5,1356,179 mins.,Musical|Romance
tt0279977,The Navigators (2001),2001,6.9,1356,96 mins.,Comedy|Drama

In [5]:
data[data['year'] == 1966]

,title,year,rating,votes,length,genres
id,,,,,,
tt0060196,"The Good, the Bad and the Ugly (1966)",1966,9.0,195238,161 mins.,Western
tt0061184,Who's Afraid of Virginia Woolf? (1966),1966,8.2,23811,131 mins.,Drama
tt0060666,Manos: The Hands of Fate (1966),1966,1.5,20927,74 mins.,Horror
tt0060827,Persona (1966),1966,8.2,20157,85 mins.,Drama|Fantasy
tt0060176,Blow-Up (1966),1966,7.6,18679,111 mins.,Drama|Mystery|Thriller
...,...,...,...,...,...,...
tt0060214,Carry on Screaming! (1966),1966,6.7,1427,97 mins.,Comedy|Horror
tt0060305,Le Deuxieme Souffle (1966),1966,8.0,1393,150 mins.,Crime|Drama
tt0060841,The Plague of the Zombies (1966),1966,6.7,1386,91 mins.,Horror
tt0061204,The Wrong Box (1966),1966,6.9,1372,105 mins.,Comedy
tt0060880,The Quiller Memorandum (1966),1966,6.5,1356,104 mins.,Drama|Mystery|Thriller

In [8]:
data[(data['year'] > 1955) & (data['year'] < 2000)]

,title,year,rating,votes,length,genres
id,,,,,,
tt0111161,The Shawshank Redemption (1994),1994,9.2,619479,142 mins.,Crime|Drama
tt0110912,Pulp Fiction (1994),1994,9.0,490065,154 mins.,Crime|Thriller
tt0137523,Fight Club (1999),1999,8.8,458173,139 mins.,Drama|Mystery|Thriller
tt0133093,The Matrix (1999),1999,8.7,448114,136 mins.,Action|Adventure|Sci-Fi
tt0109830,Forrest Gump (1994),1994,8.7,368994,142 mins.,Comedy|Drama|Romance
...,...,...,...,...,...,...
tt0101356,Another You (1991),1991,4.9,1359,98 mins.,Comedy|Crime
tt0067227,The Merchant of Four Seasons (1971),1971,7.6,1359,88 mins.,Drama
tt0118635,Aprile (1998),1998,6.7,1358,78 mins.,Comedy
tt0060880,The Quiller Memorandum (1966),1966,6.5,1356,104 mins.,Drama|Mystery|Thriller
tt0152836,Taal (1999),1999,6.5,1356,179 mins.,Musical|Romance

In [12]:
data[(data['year'] > 1955) & (data['year'] < 2000)].sort_values(by='rating', ascending=False).head(10)

,title,year,rating,votes,length,genres
id,,,,,,
tt0111161,The Shawshank Redemption (1994),1994,9.2,619479,142 mins.,Crime|Drama
tt0068646,The Godfather (1972),1972,9.2,474189,175 mins.,Crime|Drama
tt0110912,Pulp Fiction (1994),1994,9.0,490065,154 mins.,Crime|Thriller
tt0071562,The Godfather: Part II (1974),1974,9.0,291169,200 mins.,Crime|Drama
tt0252487,Outrageous Class (1975),1975,9.0,9823,87 mins.,Comedy|Drama
tt0060196,"The Good, the Bad and the Ugly (1966)",1966,9.0,195238,161 mins.,Western
tt0050083,12 Angry Men (1957),1957,8.9,148155,96 mins.,Drama|Mystery
tt0073486,One Flew Over the Cuckoo's Nest (1975),1975,8.9,255503,133 mins.,Drama
tt0108052,Schindler's List (1993),1993,8.9,325888,195 mins.,Biography|Drama|History|War
tt0099685,Goodfellas (1990),1990,8.8,270728,146 mins.,Biography|Crime|Drama|Thriller